name: chatgpt-revise
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch should be revised?'
        default: 'main'
        type: string
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.branch }} 

      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ inputs.branch }}/chatgpt-revise
